In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import pickle
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
test_file = pd.read_csv('201910test.csv')
# data = test_file.values
data = test_file.iloc[:,1:]

In [3]:
#使用前注意测试,MinMax只能针对列向量，所以必须转制后使用

data = data.T
scaler = MinMaxScaler()
data = scaler.fit_transform(data)
data = data.T

In [4]:
print(data.shape)
print(data)

(9, 2251)
[[0.06646093 0.06584616 0.06338468 ... 0.03569238 0.02830776 0.02892308]
 [0.55443164 0.52025442 0.61772025 ... 0.01392391 0.03544303 0.02278492]
 [0.092      0.088      0.0986668  ... 0.032      0.032      0.048     ]
 ...
 [0.03982303 0.04719766 0.05604721 ... 0.01179945 0.00491641 0.00786626]
 [0.0771775  0.09040793 0.09592072 ... 0.02094817 0.01212777 0.03087099]
 [0.12952144 0.14002317 0.13885643 ... 0.01633615 0.02100348 0.03967312]]


In [23]:
np.save('chem18original',data)

In [48]:
zif8_o = data[3:6,:]
zif8_o

array([[200.  , 193.33, 206.67, ..., 225.  , 233.33, 181.67],
       [198.33, 221.67, 205.  , ..., 236.67, 258.33, 183.33],
       [210.  , 200.  , 200.  , ..., 226.67, 251.67, 410.  ]])

In [49]:
np.save('zif8_o',zif8_o)

In [3]:
# Test = pd.DataFrame(data)
# Test

0       1       2       3       4       5       6       7       8     \
0   226.67  375.00  271.67  220.00  270.00  235.00  256.67  263.33  265.00   
1   260.00  238.33  250.00  260.00  256.67  250.00  268.33  255.00  213.33   
2   211.67  256.67  231.67  258.33  293.33  238.33  385.00  295.00  223.33   
3   200.00  193.33  206.67  191.67  198.33  240.00  256.67  198.33  201.67   
4   198.33  221.67  205.00  220.00  161.67  160.00  230.00  215.00  186.67   
5   210.00  200.00  200.00  210.00  205.00  241.67  193.33  221.67  215.00   
6   241.67  290.00  288.33  283.33  275.00  288.33  285.00  250.00  263.33   
7   190.00  206.67  225.00  201.67  226.67  268.33  205.00  200.00  225.00   
8   163.33  178.33  201.67  191.67  200.00  225.00  198.33  255.00  265.00   
9   211.67  165.00  208.33  410.00  238.33  165.00  265.00  160.00  183.33   
10  220.00  173.33  250.00  273.33  176.67  220.00  251.67  210.00  205.00   
11  193.33  228.33  240.00  255.00  238.33  168.33  233.33  201.67  206.67   
12  195.00  205.00  200.00  176.67  196.67  215.00  158.33  203.33  230.00   
13  226.67  210.00  203.33  213.33  250.00  195.00  216.67  261.67  210.00   
14  240.00  165.00  185.00  171.67  158.33  278.33  175.00  200.00  161.67   
15  248.33  208.33  256.67  308.33  253.33  248.33  305.00  230.00  238.33   
16  240.00  240.00  281.67  240.00  250.00  398.33  243.33  241.67  230.00   
17  308.33  290.00  196.67  258.33  226.67  248.33  218.33  291.67  241.67   

      9     ...    2241    2242    2243    2244    2245    2246    2247  \
0   266.67  ...  228.33  280.00  191.67  208.33  216.67  250.00  245.00   
1   255.00  ...  231.67  263.33  260.00  225.00  266.67  231.67  190.00   
2   235.00  ...  253.33  341.67  188.33  213.33  260.00  338.33  228.33   
3   253.33  ...  206.67  210.00  263.33  250.00  218.33  190.00  186.67   
4   236.67  ...  263.33  291.67  181.67  256.67  343.33  263.33  256.67   
5   208.33  ...  278.33  296.67  220.00  228.33  203.33  258.33  236.67   
6   240.00  ...  180.00  190.00  185.00  273.33  171.67  176.67  210.00   
7   200.00  ...  270.00  243.33  251.67  265.00  300.00  228.33  263.33   
8   186.67  ...  245.00  246.67  248.33  305.00  303.33  265.00  308.33   
9   171.67  ...  195.00  295.00  305.00  228.33  265.00  248.33  220.00   
10  221.67  ...  195.00  295.00  305.00  228.33  265.00  248.33  220.00   
11  253.33  ...  211.67  311.67  271.67  300.00  205.00  260.00  368.33   
12  178.33  ...  136.67  148.33  148.33  148.33  121.67  155.00  125.00   
13  291.67  ...  150.00  151.67  215.00  150.00  195.00  151.67  186.67   
14  193.33  ...  165.00  135.00  100.00  125.00  143.33   81.67  341.67   
15  218.33  ...  223.33  235.00  228.33  243.33  210.00  211.67  168.33   
16  226.67  ...  211.67  125.00  183.33  221.67  191.67  230.00  153.33   
17  275.00  ...  175.00  175.00  226.67  203.33  196.67  143.33  201.67   

      2248    2249    2250  
0   180.00  213.33  296.67  
1   476.67  188.33  246.67  
2   215.00  241.67  246.67  
3   225.00  233.33  181.67  
4   236.67  258.33  183.33  
5   226.67  251.67  410.00  
6   221.67  188.33  195.00  
7   288.33  235.00  280.00  
8   328.33  313.33  266.67  
9   228.33  245.00  333.33  
10  228.33  245.00  333.33  
11  243.33  238.33  276.67  
12  183.33  116.67  175.00  
13  126.67  128.33  143.33  
14   91.67  158.33  108.33  
15  203.33  195.00  221.67  
16  146.67  226.67  180.00  
17  165.00  153.33  235.00  

[18 rows x 2251 columns]

In [14]:
scaler = MinMaxScaler()
Test = scaler.fit_transform(data)

In [15]:
Test.shape

(9, 2251)

In [16]:
Test

array([[0.1140554 , 0.13483108, 0.07819926, ..., 1.        , 0.8718    ,
        0.78125176],
       [1.        , 1.        , 1.        , ..., 0.        , 0.51282308,
        0.        ],
       [0.        , 0.00842694, 0.        , ..., 0.11628085, 0.20513077,
        0.31249883],
       ...,
       [0.06100806, 0.12359544, 0.1208534 , ..., 0.37209594, 0.12820769,
        0.03124707],
       [0.01591508, 0.06741554, 0.04265414, ..., 0.11628085, 0.        ,
        0.21874824],
       [0.15119323, 0.20224662, 0.14218047, ..., 0.23256171, 0.4359    ,
        0.71874824]])

In [6]:
np.savetxt('201910test_norm_Transpose.csv', data, delimiter = ',')


In [18]:
# np.savetxt('test_data18_chem_norm.csv', Test, delimiter = ',')
np.save('chem18norm',Test)

In [22]:
Test

array([[0.43682759, 1.        , 0.83876899, ..., 0.22942857, 0.49150819,
        0.62432459],
       [0.66668966, 0.34919048, 0.62905255, ..., 1.        , 0.36438523,
        0.45858057],
       [0.33337931, 0.43652381, 0.45165973, ..., 0.32033766, 0.63561477,
        0.45858057],
       ...,
       [0.5862069 , 0.20633333, 0.69360302, ..., 0.29002597, 0.39830164,
        0.37570856],
       [0.52875862, 0.35714286, 0.93554631, ..., 0.14285714, 0.55934099,
        0.23757749],
       [1.        , 0.5952381 , 0.11293913, ..., 0.19046753, 0.1864131 ,
        0.41989591]])

# 拼接下 zif8

In [24]:
Test_1=np.load('chem18norm.npy')
Test_1 = Test_1[3:6,:2251]

In [26]:
Test_18=np.load('chem18fft.npy')
Test_2 = Test_18[0:3,:2251]
Test_3 = Test_18[6:18,:2251]

In [29]:
frames = [Test_2,Test_1,Test_3]


Test = np.concatenate(frames)

In [30]:
Test.shape

(18, 2251)

In [31]:
np.save('chem18concate',Test)

In [32]:
np.savetxt('chem18concate.csv', Test, delimiter = ',')


# 拼接未归一的数据看看结果

In [60]:
Test_o=np.load('chem18fft_ori.npy')
Test_o2=np.load('zif8_o.npy')

Test_o1 = Test_o[0:3,:2251]
Test_o2 = Test_o2[:,:2251]
Test_o3 = Test_o[6:18,:2251]

frames = [Test_o1,Test_o2,Test_o3]
Test_out = np.concatenate(frames)



In [61]:
Test_out.shape

(18, 2251)

In [56]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

Test_out = Test_out.T
# print(Data_output.shape)

scaler = MinMaxScaler()
Test_out = scaler.fit_transform(Test_out)
Test_out = Test_out.T
# print(Data_output.shape)
np.save('chem18concateV2',Test_out)

In [62]:
np.savetxt('chem18concateV2.csv', Test, delimiter = ',')


In [50]:
Test_o2=np.load('zif8_o.npy')

Test_o2.shape

(3, 2251)