In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import pickle
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
test_file = pd.read_csv('zif7.csv')
# data = test_file.values
data = test_file.iloc[:,1:]

In [3]:
#使用前注意测试,MinMax只能针对列向量，所以必须转制后使用

data = data.T
scaler = MinMaxScaler()
data = scaler.fit_transform(data)
data = data.T

In [4]:
print(data.shape)
print(data)

(3, 2251)
[[0.07516505 0.07110217 0.07313361 ... 0.02539366 0.01879122 0.02336207]
 [0.03964885 0.04358354 0.03631961 ... 0.01846244 0.01210651 0.01210651]
 [0.06780194 0.06993031 0.06445751 ... 0.0161144  0.01520227 0.01459415]]


In [5]:
np.savetxt('zif7_norm_Transpose.csv', data, delimiter = ',')
