In [3]:
import numpy as np
import pandas as pd
import pickle

In [6]:
#test_file="/home/suliangbu/work/wanghong/train_low_None_.pickle"
#tmp = np.load(test_file)

#打开一个名为data1.pkl的文件，打开方式为二进制读取(参数‘rb’)
file_to_read = open('test.pickle', 'rb')

#通过pickle的load函数读取data1.pkl中的对象，并赋值给data2
tmp = pickle.load(file_to_read)

test_data = tmp.values  
test_data

array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 'ZIF-67'],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 'ZIF-67'],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 'ZIF-67'],
       ...,
       [0.0, 0.0006296345868824865, 0.0, ..., 0.0, 0.0, 'ZIF-90'],
       [0.0, 0.03677773918217792, 0.0, ..., 0.0, 0.0, 'ZIF-71'],
       [0.0062100358145721485, 0.04958877366710038, 0.006238917333364924,
        ..., 0.008600674714482566, 0.00858628922936616, 'ZIF-71']],
      dtype=object)

In [15]:
targets, pairs = [], []
for i in range(14):
    for j in range(i + 1, 14):
        if test_data[i][-1] == test_data[j][-1]:
            pairs.append([test_data[i][:-1], test_data[j][:-1]])
            targets.append(1)
        else:
            pairs.append([test_data[i][:-1], test_data[j][:-1]])
            targets.append(0)
#print(pairs,targets)


[[array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object),
  array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object)],
 [array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object),
  array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object)],
 [array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object),
  array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object)],
 [array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object),
  array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object)],
 [array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object),
  array([0.0, 0.0, 0.0014783767030106267, ..., 0.0, 0.0, 0.0], dtype=object)],
 [array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object),
  array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object)],
 [array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object),
  array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object)],
 [array([0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0], dtype=object),
  array([0.0, 0.0869358646188851, 0.0, ..., 0.0, 0.0, 0.0], dtype=object)],